# Generated by Django 2.0.1 on 2018-11-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.TextField(verbose_name='Содержание запроса')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запрос',
                'ordering': ('datetime',),
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='SubRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='Содержание')),
                ('stopwatch', models.TimeField(blank=True, null=True, verbose_name='Замер')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertex_app.Request', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Подзапрос',
                'ordering': ('content',),
                'verbose_name_plural': 'Подзапрос',
            },
        ),
        migrations.CreateModel(
            name='SubRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код статуса')),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус подзапоса',
                'verbose_name_plural': 'Статусы подзапосов',
            },
        ),
        migrations.CreateModel(
            name='SubRequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код типа')),
                ('name', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип подзапоса',
                'verbose_name_plural': 'Типы подзапосов',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subrequesttype',
            unique_together={('code',)},
        ),
        migrations.AlterUniqueTogether(
            name='subrequeststatus',
            unique_together={('code',)},
        ),
        migrations.AddField(
            model_name='subrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertex_app.SubRequestStatus', verbose_name='Статус Подзапоса'),
        ),
        migrations.AddField(
            model_name='subrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertex_app.SubRequestType', verbose_name='Тип Подзапоса'),
        ),
        migrations.AlterUniqueTogether(
            name='subrequest',
            unique_together={('content', 'request')},
        ),
    ]
