# Generated by Django 2.0.1 on 2018-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name_plural': 'Статусы подзапосов',
                'verbose_name': 'Статус подзапоса',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subrequeststatus',
            unique_together={('code',)},
        ),
    ]
