# Generated by Django 2.0.1 on 2018-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertex_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('comment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name_plural': 'Запросы',
                'ordering': ('-datetime',),
                'verbose_name': 'Запрос',
            },
        ),
    ]
