# Generated by Django 2.0.1 on 2018-11-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertex_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubRequestType',
        ),
        migrations.AlterField(
            model_name='subrequest',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='subrequeststatus',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код статуса'),
        ),
    ]
